apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
data:
  # Fluent Bit main configuration file
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name         tail
        Path         /var/log/containers/*postgres*.log,/var/log/containers/*mysql*.log
        Parser       docker
        Tag          kube.*
        DB           /var/log/flb_kube.db
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [FILTER]
        Name         kubernetes
        Match        kube.*
        Kube_URL     https://kubernetes.default.svc:443
        Kube_Tag_Prefix kube.var.log.containers
        Merge_Log    On
        Keep_Log     Off
        Annotations  Off

    [OUTPUT]
        Name         es
        Match        *
        Host         elasticsearch
        Port         9200
        Index        postgres-mysql-logs
        Type         _doc
        Logstash_Format On
        Retry_Limit  False

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        Decode_Field_As escaped_utf8 log
        Decode_Field_As json log
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: default
  labels:
    k8s-app: fluent-bit
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit
  template:
    metadata:
      labels:
        k8s-app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:1.8
          resources:
            limits:
              memory: 200Mi
              cpu: 500m
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: config
              mountPath: /fluent-bit/etc/
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch" # Change if using an external Elasticsearch host
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: config
          configMap:
            name: fluent-bit-config
