apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info

    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Parser        docker
        Tag           kube.*
        Refresh_Interval 5
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
        DB            /var/log/flb_kube.db

    [FILTER]
        Name          kubernetes
        Match         kube.*
        Kube_URL      https://kubernetes.default.svc:443
        Merge_Log     On
        K8S-Logging.Parser On

    [OUTPUT]
        Name          http
        Match         kube.*
        Host          192.168.49.2   # Replace with Minikube IP
        Port          3000
        URI           /logs
        Format        json_lines
        tls           off
